version: "3"
services:
    web:
        build: .
        ports: 
            - "8888:8888"
    mysql:
        image: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
    
